-- ------------------------- info -------------------------
-- @@ver: 1_000_000
-- @@info: 初始化fa-doc模块
-- ------------------------- info -------------------------

CREATE TABLE IF NOT EXISTS "dm_doc" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NOT NULL,
  "is_public" boolean NOT NULL DEFAULT FALSE,
  "share_code" varchar(32) DEFAULT NULL,
  "view_num" integer DEFAULT 0,
  "view_chapter_num" integer DEFAULT 0,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "dm_doc" IS 'DOC-文档';
COMMENT ON COLUMN "dm_doc"."id" IS 'ID';
COMMENT ON COLUMN "dm_doc"."name" IS '文档名称';
COMMENT ON COLUMN "dm_doc"."is_public" IS '是否公开';
COMMENT ON COLUMN "dm_doc"."share_code" IS '分享码';
COMMENT ON COLUMN "dm_doc"."view_num" IS '访问次数';
COMMENT ON COLUMN "dm_doc"."view_chapter_num" IS '章节总访问次数';
COMMENT ON COLUMN "dm_doc"."crt_time" IS '创建时间';
COMMENT ON COLUMN "dm_doc"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "dm_doc"."crt_name" IS '创建用户';
COMMENT ON COLUMN "dm_doc"."crt_host" IS '创建IP';
COMMENT ON COLUMN "dm_doc"."upd_time" IS '更新时间';
COMMENT ON COLUMN "dm_doc"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "dm_doc"."upd_name" IS '更新用户';
COMMENT ON COLUMN "dm_doc"."upd_host" IS '更新IP';
COMMENT ON COLUMN "dm_doc"."deleted" IS '是否删除';

CREATE TABLE IF NOT EXISTS "dm_doc_chapter" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "parent_id" integer NOT NULL,
  "doc_id" integer NOT NULL,
  "name" varchar(255) NOT NULL,
  "sort" integer NOT NULL DEFAULT 0,
  "view_num" integer DEFAULT 0,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "dm_doc_chapter" IS 'DOC-文档章节';
COMMENT ON COLUMN "dm_doc_chapter"."id" IS 'ID';
COMMENT ON COLUMN "dm_doc_chapter"."parent_id" IS '父ID';
COMMENT ON COLUMN "dm_doc_chapter"."doc_id" IS '文档ID';
COMMENT ON COLUMN "dm_doc_chapter"."name" IS '章节名称';
COMMENT ON COLUMN "dm_doc_chapter"."sort" IS '排序';
COMMENT ON COLUMN "dm_doc_chapter"."view_num" IS '访问次数';
COMMENT ON COLUMN "dm_doc_chapter"."crt_time" IS '创建时间';
COMMENT ON COLUMN "dm_doc_chapter"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "dm_doc_chapter"."crt_name" IS '创建用户';
COMMENT ON COLUMN "dm_doc_chapter"."crt_host" IS '创建IP';
COMMENT ON COLUMN "dm_doc_chapter"."upd_time" IS '更新时间';
COMMENT ON COLUMN "dm_doc_chapter"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "dm_doc_chapter"."upd_name" IS '更新用户';
COMMENT ON COLUMN "dm_doc_chapter"."upd_host" IS '更新IP';
COMMENT ON COLUMN "dm_doc_chapter"."deleted" IS '是否删除';

CREATE TABLE IF NOT EXISTS "dm_doc_chapter_detail" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "content" text NOT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "dm_doc_chapter_detail" IS 'DOC-文档章节详情';
COMMENT ON COLUMN "dm_doc_chapter_detail"."id" IS 'ID';
COMMENT ON COLUMN "dm_doc_chapter_detail"."content" IS '章节富文本内容';
COMMENT ON COLUMN "dm_doc_chapter_detail"."crt_time" IS '创建时间';
COMMENT ON COLUMN "dm_doc_chapter_detail"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "dm_doc_chapter_detail"."crt_name" IS '创建用户';
COMMENT ON COLUMN "dm_doc_chapter_detail"."crt_host" IS '创建IP';
COMMENT ON COLUMN "dm_doc_chapter_detail"."upd_time" IS '更新时间';
COMMENT ON COLUMN "dm_doc_chapter_detail"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "dm_doc_chapter_detail"."upd_name" IS '更新用户';
COMMENT ON COLUMN "dm_doc_chapter_detail"."upd_host" IS '更新IP';

CREATE TABLE IF NOT EXISTS "dm_doc_chapter_his" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "doc_id" integer NOT NULL,
  "chapter_id" integer NOT NULL,
  "name" varchar(255) DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "dm_doc_chapter_his" IS 'DOC-章节历史';
COMMENT ON COLUMN "dm_doc_chapter_his"."id" IS 'ID';
COMMENT ON COLUMN "dm_doc_chapter_his"."doc_id" IS '文档ID';
COMMENT ON COLUMN "dm_doc_chapter_his"."chapter_id" IS '章节ID';
COMMENT ON COLUMN "dm_doc_chapter_his"."name" IS '版本名称';
COMMENT ON COLUMN "dm_doc_chapter_his"."crt_time" IS '创建时间';
COMMENT ON COLUMN "dm_doc_chapter_his"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "dm_doc_chapter_his"."crt_name" IS '创建用户';
COMMENT ON COLUMN "dm_doc_chapter_his"."crt_host" IS '创建IP';
COMMENT ON COLUMN "dm_doc_chapter_his"."upd_time" IS '更新时间';
COMMENT ON COLUMN "dm_doc_chapter_his"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "dm_doc_chapter_his"."upd_name" IS '更新用户';
COMMENT ON COLUMN "dm_doc_chapter_his"."upd_host" IS '更新IP';
COMMENT ON COLUMN "dm_doc_chapter_his"."deleted" IS '是否删除';

CREATE TABLE IF NOT EXISTS "dm_doc_chapter_his_detail" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "content" text NOT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "dm_doc_chapter_his_detail" IS 'DOC-章节历史详情';
COMMENT ON COLUMN "dm_doc_chapter_his_detail"."id" IS 'ID';
COMMENT ON COLUMN "dm_doc_chapter_his_detail"."content" IS '章节历史富文本内容';
COMMENT ON COLUMN "dm_doc_chapter_his_detail"."crt_time" IS '创建时间';
COMMENT ON COLUMN "dm_doc_chapter_his_detail"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "dm_doc_chapter_his_detail"."crt_name" IS '创建用户';
COMMENT ON COLUMN "dm_doc_chapter_his_detail"."crt_host" IS '创建IP';

CREATE TABLE IF NOT EXISTS "dm_doc_user" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "doc_id" integer NOT NULL,
  "user_id" varchar(32) NOT NULL DEFAULT '0',
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "dm_doc_user" IS 'DOC-文档用户';
COMMENT ON COLUMN "dm_doc_user"."id" IS 'ID';
COMMENT ON COLUMN "dm_doc_user"."doc_id" IS '文档ID';
COMMENT ON COLUMN "dm_doc_user"."user_id" IS '用户ID';
COMMENT ON COLUMN "dm_doc_user"."crt_time" IS '创建时间';
COMMENT ON COLUMN "dm_doc_user"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "dm_doc_user"."crt_name" IS '创建用户';
COMMENT ON COLUMN "dm_doc_user"."crt_host" IS '创建IP';
COMMENT ON COLUMN "dm_doc_user"."upd_time" IS '更新时间';
COMMENT ON COLUMN "dm_doc_user"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "dm_doc_user"."upd_name" IS '更新用户';
COMMENT ON COLUMN "dm_doc_user"."upd_host" IS '更新IP';
COMMENT ON COLUMN "dm_doc_user"."deleted" IS '是否删除';

INSERT INTO "base_rbac_menu" (
  "id", "parent_id", "name", "sort", "level", "icon", "status", "link_type", "link_url",
  "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted"
) VALUES
  (28000000, 0, '文档管理', 1, 0, 'book', TRUE, 1, '/admin/dm', '2023-06-30 16:59:00', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE),
  (28010000, 28000000, '文档管理', 0, 1, 'book', TRUE, 1, '/admin/dm/doc/doc', '2023-06-30 17:00:28', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE),
  (28010100, 28010000, '查看', 0, 9, NULL, TRUE, 1, '/admin/dm/doc/view/:id', '2023-07-26 16:54:18', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE),
  (28010200, 28010000, '编辑', 1, 9, NULL, TRUE, 1, '/admin/dm/doc/edit/:id', '2023-07-26 17:38:17', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE)
ON CONFLICT ("id") DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('base_rbac_menu', 'id'),
    COALESCE((SELECT MAX("id") FROM "base_rbac_menu"), 1),
    TRUE
);
